site_name: EasyBuild blog
theme:
  name: material
  logo: img/logos/EasyBuild.png
  favicon: img/logos/EasyBuild.png
nav:
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
plugins:
  - blog:
      archive: false
      blog_dir: .
      blog_toc: true
